### ISSUE TITLE
When selecting answer on the front page of a codelab the page goes back to the top

### ISSUE THREAD

**Issue by campbieil** [ubuntu/codelabs#3] opened 2016-09-27 07:40 UTC
At the bottom of the first page of a codelabd is a form:
_How will you use this tutorial?
- Only read through it
- Read it and complete the exercises_

When selecting Only read through it the page scrolls to the top rather than leaving the focus on the form itself

**Comment by didrocks** [comment] 2016-09-29 07:38
This should be now be fixed on master.
Note that I didn't reproduce it at 100%. I did try though the fix on various browsers (chrome unstable, stable and firefox) and it seems to behave as expected.

Do not hesitate to reopen a bug after next snap release if this isn't fixed for you!

**Closed as completed by didrocks** 2016-09-29 07:38 UTC
